Biblioteka_bazyDanych/Controllers/czytelnicyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Biblioteka_bazyDanych;
using PagedList;
using PagedList.Mvc;

namespace Biblioteka_bazyDanych.Controllers
{
    public class czytelnicyController : Controller
    {
        private bibliotekaEntities1 db = new bibliotekaEntities1();

        // GET: czytelnicy
        public ActionResult Index(string option, string search, int? page, string sort)
        {
            List<SelectListItem> searchOptions = new List<SelectListItem>();
            var data = new[]{
                 new SelectListItem{ Value="",Text=""},
                 new SelectListItem{ Value="Imię" ,Text="Imię"},
                 new SelectListItem{ Value="Nazwisko",Text="Nazwisko"},
                 new SelectListItem{ Value="Miasto",Text="Miasto"},
                 new SelectListItem{ Value="Ulica",Text="Ulica"},
                 new SelectListItem{ Value="Liczba książek",Text="Liczba książek"},
             };
            searchOptions = data.ToList();

            ViewBag.option = searchOptions;

            ViewBag.SortByID = string.IsNullOrEmpty(sort) ? "descending id" : "";
            ViewBag.SortByName = sort == "Imię" ? "descending imie" : "Imię";
            ViewBag.SortBySurname = sort == "Nazwisko" ? "descending nazwisko" : "Nazwisko";
            ViewBag.SortByCity = sort == "Miasto" ? "descending miasto" : "Miasto";
            ViewBag.SortByStreet = sort == "Ulica" ? "descending ulica" : "Liczba ulica";
            ViewBag.SortByBooks = sort == "Liczba książek" ? "descending books" : "Liczba książek";

            //here we are converting the db.autorzy to AsQueryable so that we can invoke all the extension methods on variable records.  
            var records = db.czytelnicy.AsQueryable();

            if (option == "Imię")
            {
                records = records.Where(x => x.imie == search || search == null);
            }
            else if (option == "Nazwisko")
            {
                records = records.Where(x => x.nazwisko == search || search == null);
            }
            else if (option == "Miasto")
            {
                records = records.Where(x => x.miastso == search || search == null);
            }
            else if (option == "Ulica")
            {
                records = records.Where(x => x.ulica == search || search == null);
            }
            else if (option == "Liczba książek")
            {
                records = records.Where(x => x.liczba_ksiazek.ToString() == search || search == null);
            }

            switch (sort)
            {
                case "descending id":
                    records = records.OrderByDescending(x => x.id_czytelnika);
                    break;

                case "descending imie":
                    records = records.OrderByDescending(x => x.imie);
                    break;

                case "Imię":
                    records = records.OrderBy(x => x.imie);
                    break;

                case "descending nazwisko":
                    records = records.OrderByDescending(x => x.nazwisko);
                    break;

                case "Nazwisko":
                    records = records.OrderBy(x => x.nazwisko);
                    break;

                case "descending miasto":
                    records = records.OrderByDescending(x => x.miastso);
                    break;

                case "Miasto":
                    records = records.OrderBy(x => x.miastso);
                    break;

                case "descending ulica":
                    records = records.OrderByDescending(x => x.ulica);
                    break;

                case "Ulica":
                    records = records.OrderBy(x => x.ulica);
                    break;
                case "descending books":
                    records = records.OrderByDescending(x => x.liczba_ksiazek);
                    break;

                case "Liczba książek":
                    records = records.OrderBy(x => x.liczba_ksiazek);
                    break;
                default:
                    records = records.OrderBy(x => x.id_czytelnika);
                    break;

            }
            return View(records.ToPagedList(page ?? 1, 10));

        }

        // GET: czytelnicy/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            czytelnicy czytelnicy = db.czytelnicy.Find(id);
            if (czytelnicy == null)
            {
                return HttpNotFound();
            }
            ViewBag.Read = ReadBooks((int)id);
            ViewBag.Reserved = ReservedBooks((int)id);
            ViewBag.Borrowed = BorrowedBooks((int)id);
            return View(czytelnicy);
        }

        // GET: czytelnicy/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: czytelnicy/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_czytelnika,imie,nazwisko,miastso,ulica,liczba_ksiazek")] czytelnicy czytelnicy)
        {
            if (ModelState.IsValid)
            {
                czytelnicy.liczba_ksiazek = 0;
                db.czytelnicy.Add(czytelnicy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(czytelnicy);
        }

        // GET: czytelnicy/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            czytelnicy czytelnicy = db.czytelnicy.Find(id);
            if (czytelnicy == null)
            {
                return HttpNotFound();
            }
            return View(czytelnicy);
        }

        // POST: czytelnicy/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_czytelnika,imie,nazwisko,miastso,ulica,liczba_ksiazek")] czytelnicy czytelnicy)
        {
            if (ModelState.IsValid)
            {
                czytelnicy.liczba_ksiazek = db.wypozyczenia.Where(x => x.id_czytelnika == czytelnicy.id_czytelnika).Where(x=>x.status == "Wypożyczone").Select(x => x.id_ksiazki).Count();
                db.Entry(czytelnicy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(czytelnicy);
        }

        // GET: czytelnicy/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            czytelnicy czytelnicy = db.czytelnicy.Find(id);
            if (czytelnicy == null)
            {
                return HttpNotFound();
            }
            return View(czytelnicy);
        }

        // POST: czytelnicy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            czytelnicy czytelnicy = db.czytelnicy.Find(id);
            db.czytelnicy.Remove(czytelnicy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public int ReadBooks(int id)
        {
            return db.wypozyczenia.Where(x => x.id_czytelnika == id).Where(x => x.status == "Zwrócone").Select(x => x.id_wypozyczenia).Count();
        }
        public int ReservedBooks(int id)
        {
            return db.wypozyczenia.Where(x => x.id_czytelnika == id).Where(x => x.status == "Zarezerwowane").Select(x => x.id_wypozyczenia).Count();     
        }
        public int BorrowedBooks(int id)
        {
            return db.wypozyczenia.Where(x => x.id_czytelnika == id).Where(x => x.status == "Wypożyczone").Select(x => x.id_wypozyczenia).Count();
        }
    }
}

Biblioteka_bazyDanych/Views/czytelnicy/Create.cshtml
@model Biblioteka_bazyDanych.czytelnicy

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>czytelnicy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miastso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miastso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miastso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ulica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ulica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ulica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Biblioteka_bazyDanych/Views/czytelnicy/Delete.cshtml
@model Biblioteka_bazyDanych.czytelnicy

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>czytelnicy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.miastso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.miastso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ulica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ulica)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.liczba_ksiazek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.liczba_ksiazek)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Biblioteka_bazyDanych/Views/czytelnicy/Details.cshtml
@model Biblioteka_bazyDanych.czytelnicy

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>czytelnicy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.miastso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.miastso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ulica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ulica)
        </dd>
        <dt>
            Przeczytane książki
        </dt>
        <dd>
            @ViewBag.Read
        </dd>
        <dt>
            Zarezerwowane książki
        </dt>
        <dd>
            @ViewBag.Reserved
        </dd>
        <dt>
            Aktualnie wypożyczone
        </dt>
        <dd>
            @ViewBag.Borrowed
        </dd>
    </dl>

    <h3>Historia wypożyczeń</h3>

    @if (Model.wypozyczenia.Count() == 0)
    {

        <h5>Czytelnik nie wypożyczał jeszcze książek.</h5>

    }
    else
    {
        <table class="table">
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Data zamówienia
                </th>
                <th>
                    Data wypożyczenia
                </th>
                <th>
                    Data zwrotu
                </th>
                <th>
                    Status
                </th>
                <th>
                    Czytelnik
                </th>
                <th>
                    Książka
                </th>
            </tr>

            @foreach (var item in Model.wypozyczenia)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id_wypozyczenia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.data_zamowienia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.data_wypozyczenia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.data_zwrotu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @Html.ActionLink(item.czytelnicy.imie + " " + item.czytelnicy.nazwisko, "Details", "czytelnicy", new { id = item.id_czytelnika }, null)
            </td>
            <td>
                @Html.ActionLink(item.ksiazki.tytul, "Details", "ksiazki", new { id = item.id_ksiazki }, null)
            </td>
        </tr>

             }
        </table>
    }

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_czytelnika }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Biblioteka_bazyDanych/Views/czytelnicy/Edit.cshtml
@model Biblioteka_bazyDanych.czytelnicy

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>czytelnicy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_czytelnika)

        <div class="form-group">
            @Html.LabelFor(model => model.imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miastso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miastso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miastso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ulica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ulica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ulica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Biblioteka_bazyDanych/Views/czytelnicy/Index.cshtml
@using PagedList;

@using PagedList.Mvc;

@model IPagedList<Biblioteka_bazyDanych.czytelnicy>

@{
    ViewBag.Title = "Index";
}

<h2>Czytelnicy</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Czytelnicy", FormMethod.Get))
{
    //the following are search options
    <b> Wyszukaj wg elementu: </b>
    @Html.DropDownList("option", null, htmlAttributes: new { @class = "form-controlSearch" })
    @Html.TextBox("search", null, htmlAttributes: new { @class = "form-controlSearch" }) <input type="submit" name="submit" value="Szukaj" />
}

<br />
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("ID", "Index", new
            {
                sort = ViewBag.SortByID,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
        </th>
        <th>
            @Html.ActionLink("Imię", "Index", new
            {
                sort = ViewBag.SortByName,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
        </th>
        <th>
            @Html.ActionLink("Nazwisko", "Index", new
            {
                sort = ViewBag.SortBySurname,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
        </th>
        <th>
            @Html.ActionLink("Miasto", "Index", new
            {
                sort = ViewBag.SortByCity,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
        </th>
        <th>
            @Html.ActionLink("Ulica", "Index", new
            {
                sort = ViewBag.SortByStreet,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
        </th>
        <th>
            @Html.ActionLink("Liczba książek", "Index", new
            {
                sort = ViewBag.SortByBooks,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
        </th>
        <th></th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="7"> Brak wyników pasujących do kryterium wyszukiwania </td>
        </tr>
    }
    else
    {

        foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id_czytelnika)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.imie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nazwisko)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.miastso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ulica)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.liczba_ksiazek)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id_czytelnika }) |
                @Html.ActionLink("Details", "Details", new { id = item.id_czytelnika }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id_czytelnika })
            </td>
        </tr>
        }
    }
</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new
{
page,
option = Request.QueryString["option"],
search = Request.QueryString["search"],
sort = Request.QueryString["sort"]
}))