Biblioteka_bazyDanych/Controllers/ksiazkiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Biblioteka_bazyDanych;
using PagedList;
using PagedList.Mvc;

namespace Biblioteka_bazyDanych.Controllers
{
    public class ksiazkiController : Controller
    {
        private bibliotekaEntities1 db = new bibliotekaEntities1();

        // GET: ksiazki

        public ActionResult Index(string option, string search, int? page, string sort)
        {
            List<SelectListItem> searchOptions = new List<SelectListItem>();
            var data = new[]{
                 new SelectListItem{ Value="",Text=""},
                 new SelectListItem{ Value="Tytul" ,Text="Tytuł"},
                 new SelectListItem{ Value="Autor",Text="Autor"},
                 new SelectListItem{ Value="Gatunek",Text="Gatunek"},
                 new SelectListItem{ Value="Wydawnictwo",Text="Wydawnictwo"},
             };
            searchOptions = data.ToList();

            ViewBag.option = searchOptions;

            ViewBag.SortByID = string.IsNullOrEmpty(sort) ? "descending id" : "";
            ViewBag.SortByTitle = sort == "Tytul" ? "descending tytul" : "Tytul";
            ViewBag.SortByAuthor = sort == "Autor" ? "descending autor" : "Autor";
            ViewBag.SortByKind = sort == "Gatunek" ? "descending gatunek" : "Gatunek";
            ViewBag.SortByPress = sort == "Wydawnictwo" ? "descending wydawnictwo" : "Wydawnictwo";
            ViewBag.SortByStatus = sort == "Status" ? "descending status" : "Status";

            //here we are converting the db.autorzy to AsQueryable so that we can invoke all the extension methods on variable records.  
            var records = db.ksiazki.Include(k => k.autorzy).Include(k => k.gatunki).Include(k => k.wydawnictwa).AsQueryable();

            if (option == "Tytul")
            {
                records = records.Where(x => x.tytul == search || search == null);
            }
            else if (option == "Autor")
            {
                records = records.Where(x => x.autorzy.imie + " "+x.autorzy.nazwisko == search || x.autorzy.nazwisko == search || x.autorzy.imie == search || search == null);
            }
            else if (option == "Gatunek")
            {
                records = records.Where(x => x.gatunek == search || search == null);
            }
            else if (option == "Wydawnictwo")
            {
                records = records.Where(x => x.wydawnictwo == search || search == null);
            }

            switch (sort)
            {
                case "descending id":
                    records = records.OrderByDescending(x => x.id_ksiazki);
                    break;

                case "descending tytul":
                    records = records.OrderByDescending(x => x.tytul);
                    break;

                case "Tytul":
                    records = records.OrderBy(x => x.tytul);
                    break;

                case "descending autor":
                    records = records.OrderByDescending(x => x.autorzy.nazwisko).ThenBy(x => x.autorzy.imie);
                    break;

                case "Autor":
                    records = records.OrderBy(x => x.autorzy.nazwisko).ThenBy(x => x.autorzy.imie);
                    break;

                case "descending gatunek":
                    records = records.OrderByDescending(x => x.gatunek);
                    break;

                case "Gatunek":
                    records = records.OrderBy(x => x.gatunek);
                    break;

                case "descending wydawnictwo":
                    records = records.OrderByDescending(x => x.wydawnictwo);
                    break;

                case "Wydawnictwo":
                    records = records.OrderBy(x => x.wydawnictwo);
                    break;
                case "descending status":
                    records = records.OrderByDescending(x => x.status);
                    break;

                case "Status":
                    records = records.OrderBy(x => x.status);
                    break;
                default:
                    records = records.OrderBy(x => x.id_ksiazki);
                    break;

            }
            return View(records.ToPagedList(page ?? 1, 10));

        }

        // GET: ksiazki/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ksiazki ksiazki = db.ksiazki.Find(id);
            if (ksiazki == null)
            {
                return HttpNotFound();
            }
            return View(ksiazki);
        }

        // GET: ksiazki/Create
        public ActionResult Create()
        {
            IEnumerable<SelectListItem> items = db.autorzy.Select(c => new SelectListItem
            {
                Value = c.id_autora.ToString(),
                Text = c.imie +" "+c.nazwisko

            });

            ViewBag.id_autora = items;
            ViewBag.gatunek = new SelectList(db.gatunki, "nazwa", "nazwa");
            ViewBag.wydawnictwo = new SelectList(db.wydawnictwa, "nazwa", "nazwa");
            return View();
        }

        // POST: ksiazki/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_ksiazki,id_autora,wydawnictwo,gatunek,tytul,status")] ksiazki ksiazki)
        {
            if (ModelState.IsValid)
            {
                ksiazki.status = "Dostępna";   
                db.ksiazki.Add(ksiazki);
                UpdateBooksCount(ksiazki.id_autora);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.id_autora = new SelectList(db.autorzy, "id_autora", "imie", ksiazki.id_autora);
            ViewBag.gatunek = new SelectList(db.gatunki, "nazwa", "nazwa", ksiazki.gatunek);
            ViewBag.wydawnictwo = new SelectList(db.wydawnictwa, "nazwa", "nazwa", ksiazki.wydawnictwo);
            return View(ksiazki);
        }


        // GET: ksiazki/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ksiazki ksiazki = db.ksiazki.Find(id);
            if (ksiazki == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_autora = new SelectList(db.autorzy, "id_autora", "imie", ksiazki.id_autora);
            ViewBag.gatunek = new SelectList(db.gatunki, "nazwa", "nazwa", ksiazki.gatunek);
            ViewBag.wydawnictwo = new SelectList(db.wydawnictwa, "nazwa", "kraj", ksiazki.wydawnictwo);
            return View(ksiazki);
        }

        // POST: ksiazki/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_ksiazki,id_autora,wydawnictwo,gatunek,tytul,status")] ksiazki ksiazki)
        {

            if (ModelState.IsValid)
            {
                db.Entry(ksiazki).State = EntityState.Modified;
                UpdateBooksCount(ksiazki.id_autora);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

           
                
            ViewBag.id_autora = new SelectList(db.autorzy, "id_autora", "imie", ksiazki.id_autora);
            ViewBag.gatunek = new SelectList(db.gatunki, "nazwa", "nazwa", ksiazki.gatunek);
            ViewBag.wydawnictwo = new SelectList(db.wydawnictwa, "nazwa", "kraj", ksiazki.wydawnictwo);
            return View(ksiazki);
        }

        // GET: ksiazki/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ksiazki ksiazki = db.ksiazki.Find(id);
            if (ksiazki == null)
            {
                return HttpNotFound();
            }
            return View(ksiazki);
        }

        // POST: ksiazki/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ksiazki ksiazki = db.ksiazki.Find(id);
            db.ksiazki.Remove(ksiazki);
            UpdateBooksCount(ksiazki.id_autora);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void UpdateBooksCount(int id_autora)
        {
            var modifyAuthor = db.autorzy.Where(x => x.id_autora == id_autora).FirstOrDefault();
            modifyAuthor.liczba_dziel = db.ksiazki.Where(x => x.id_autora == modifyAuthor.id_autora).Select(x => x.id_ksiazki).Count();
            db.Entry(modifyAuthor).State = EntityState.Modified;
        }
    }
}

Biblioteka_bazyDanych/Views/wypozyczenia/Create.cshtml
@model Biblioteka_bazyDanych.wypozyczenia

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>wypozyczenia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_czytelnika, "Czytelnik", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_czytelnika", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_czytelnika, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_ksiazki, "Książka", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_ksiazki", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_ksiazki, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_zamowienia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.data_zamowienia, "{date:dd/MM/yyyy}", new { type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.data_zamowienia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_wypozyczenia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.data_wypozyczenia, "{0:yyyy-MM-dd}", new { type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.data_wypozyczenia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_zwrotu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.data_zwrotu, "{0:yyyy-MM-dd}", new { type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.data_zwrotu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("status", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Biblioteka_bazyDanych/Views/wypozyczenia/Create2.cshtml
@model Biblioteka_bazyDanych.wypozyczenia

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>wypozyczenia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_czytelnika, "Czytelnik", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_czytelnika", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_czytelnika, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_ksiazki, "Książka", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_ksiazki", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_ksiazki, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_zamowienia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.data_zamowienia, "{date:dd/MM/yyyy}", new { @Value = "14.02.2019",type = "date", @class = "form-control"})
                @Html.ValidationMessageFor(model => model.data_zamowienia, "Wybrana książka może być zarezerwowana co najmniej 31 dni od ostatniej rezerwacji.", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("status", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create2" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Biblioteka_bazyDanych/Views/wypozyczenia/Delete.cshtml
@model Biblioteka_bazyDanych.wypozyczenia

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>wypozyczenia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.data_zamowienia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_zamowienia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data_wypozyczenia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_wypozyczenia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data_zwrotu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_zwrotu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.czytelnicy.imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.czytelnicy.imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ksiazki.wydawnictwo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ksiazki.wydawnictwo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Biblioteka_bazyDanych/Views/wypozyczenia/Details.cshtml
@model Biblioteka_bazyDanych.wypozyczenia

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>wypozyczenia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.data_zamowienia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_zamowienia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data_wypozyczenia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_wypozyczenia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data_zwrotu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_zwrotu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.czytelnicy.imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.czytelnicy.imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ksiazki.wydawnictwo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ksiazki.wydawnictwo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_wypozyczenia }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Biblioteka_bazyDanych/Views/wypozyczenia/Edit.cshtml
@model Biblioteka_bazyDanych.wypozyczenia

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>wypozyczenia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_wypozyczenia)

        <div class="form-group">
            @Html.LabelFor(model => model.id_czytelnika, "id_czytelnika", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_czytelnika", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_czytelnika, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_ksiazki, "id_ksiazki", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_ksiazki", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_ksiazki, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_zamowienia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.data_zamowienia, "{0:yyyy-MM-dd}", new { type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.data_zamowienia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_wypozyczenia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.data_wypozyczenia, "{0:yyyy-MM-dd}", new { type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.data_wypozyczenia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_zwrotu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.data_zwrotu, "{0:yyyy-MM-dd}", new { type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.data_zwrotu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("status", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Biblioteka_bazyDanych/Views/wypozyczenia/Index.cshtml
@using PagedList
@using PagedList.Mvc

@model IPagedList<Biblioteka_bazyDanych.wypozyczenia>

@{
    ViewBag.Title = "Index";
}

<h2>Wypożyczenia</h2>

<p>
    @Html.ActionLink("Dodaj wypożyczenie", "Create")
</p>
<p>
    @Html.ActionLink("Dodaj rezerwację", "Create2")
</p>

@using (Html.BeginForm("Index", "Wypozyczenia", FormMethod.Get))
{
    //the following are search options
    <b> Wyszukaj wg elementu: </b>
    @Html.DropDownList("option", null, htmlAttributes: new { @class = "form-controlSearch" })
    @Html.TextBox("search", null, htmlAttributes: new { @class = "form-controlSearch" }) <input type="submit" name="submit" value="Szukaj" />
}
<br />
@using (Html.BeginForm("Index", "Wypozyczenia", FormMethod.Get))
{
    //the following are search options
    <b> Wyszukaj wg daty pomiędzy: </b>
    @Html.TextBox("option1", "{date:dd/MM/yyyy}", new { type = "date", @class = "form-controlSearch" })
    <span>a</span> @Html.TextBox("option2", "{date:dd/MM/yyyy}", new { type = "date", @class = "form-controlSearch" })
    <input type="submit" name="submit" value="Szukaj" />
}
<br />
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("ID", "Index", new
                {
                    sort = ViewBag.SortByID,
                    option = Request.QueryString["option"],
                    option1 = Request.QueryString["option1"],
                    option2 = Request.QueryString["option2"],
                    search = Request.QueryString["search"]
                })
        </th>
        <th>
            @Html.ActionLink("Data zamówienia", "Index", new
                {
                    sort = ViewBag.SortByDateOrder,
                    option = Request.QueryString["option"],
                    option1 = Request.QueryString["option1"],
                    option2 = Request.QueryString["option2"],
                    search = Request.QueryString["search"]
                })
        </th>
        <th>
            @Html.ActionLink("Data wypożyczenia", "Index", new
                {
                    sort = ViewBag.SortByDateWith,
                    option = Request.QueryString["option"],
                    option1 = Request.QueryString["option1"],
                    option2 = Request.QueryString["option2"],
                    search = Request.QueryString["search"]
                })
        </th>
        <th>
            @Html.ActionLink("Data zwrotu", "Index", new
                {
                    sort = ViewBag.SortByDateTake,
                    option = Request.QueryString["option"],
                    option1 = Request.QueryString["option1"],
                    option2 = Request.QueryString["option2"],
                    search = Request.QueryString["search"]
                })
        </th>
        <th>
            @Html.ActionLink("Status", "Index", new
                {
                    sort = ViewBag.SortByStatus,
                    option = Request.QueryString["option"],
                    option1 = Request.QueryString["option1"],
                    option2 = Request.QueryString["option2"],
                    search = Request.QueryString["search"]
                })
        </th>
        <th>
            @Html.ActionLink("Czytelnik", "Index", new
                {
                    sort = ViewBag.SortByReader,
                    option = Request.QueryString["option"],
                    option1 = Request.QueryString["option1"],
                    option2 = Request.QueryString["option2"],
                    search = Request.QueryString["search"]
                })
        </th>
        <th>
            @Html.ActionLink("Książka", "Index", new
                {
                    sort = ViewBag.SortByBook,
                    option = Request.QueryString["option"],
                    option1 = Request.QueryString["option1"],
                    option2 = Request.QueryString["option2"],
                    search = Request.QueryString["search"]
                })
        </th>
        <th></th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="8"> Brak wyników pasujących do kryterium wyszukiwania </td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id_wypozyczenia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.data_zamowienia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.data_wypozyczenia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.data_zwrotu)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.status)
                </td>
                <td>
                    @Html.ActionLink(item.czytelnicy.imie + " " + item.czytelnicy.nazwisko, "Details", "czytelnicy", new { id = item.id_czytelnika }, null)
                </td>
                <td>
                    @Html.ActionLink(item.ksiazki.tytul, "Details", "ksiazki", new { id = item.id_ksiazki }, null)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id_wypozyczenia }) |
                    @Html.ActionLink("Details", "Details", new { id = item.id_wypozyczenia }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id_wypozyczenia })
                </td>
            </tr>
        }
    }
</table>