Biblioteka_bazyDanych/Controllers/autorzyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Biblioteka_bazyDanych;
using PagedList;
using PagedList.Mvc;
using System.Data.SqlClient;

namespace Biblioteka_bazyDanych.Controllers
{
    public class autorzyController : Controller
    {
        private bibliotekaEntities1 db = new bibliotekaEntities1();

        // GET: autorzy
        /*public ActionResult Index()
        {
            return View(db.autorzy.ToList());
        }*/

        public ActionResult Index(string option, string search, int? page, string sort)
        {
            List<SelectListItem> searchOptions = new List<SelectListItem>();
            var data = new[]{
                 new SelectListItem{ Value="",Text=""},
                 new SelectListItem{ Value="Imię" ,Text="Imię"},
                 new SelectListItem{ Value="Nazwisko",Text="Nazwisko"},
                 new SelectListItem{ Value="Narodowość",Text="Narodowość"},
             };
            searchOptions = data.ToList();

            ViewBag.option = searchOptions;

            //if the sort parameter is null or empty then we are initializing the value as descending name  
            ViewBag.SortByID = string.IsNullOrEmpty(sort) ? "descending id" : "";
            ViewBag.SortByName = sort == "Imię" ? "descending imie" : "Imię";
            //if the sort value is gender then we are initializing the value as descending gender  
            ViewBag.SortBySurname = sort == "Nazwisko" ? "descending nazwisko" : "Nazwisko";
            ViewBag.SortByNationality = sort == "Narodowość" ? "descending narodowosc" : "Narodowość";
            ViewBag.SortByBooks = sort == "Liczba Dzieł" ? "descending dziela" : "Liczba Dzieł";

            //here we are converting the db.autorzy to AsQueryable so that we can invoke all the extension methods on variable records.  
            var records = db.autorzy.AsQueryable();

            if (option == "Imię")
            {
                records = records.Where(x => x.imie == search || search == null);
            }
            else if (option == "Nazwisko")
            {
                records = records.Where(x => x.nazwisko == search || search == null);
            }
            else if (option == "Narodowość")
            {
                records = records.Where(x => x.narodowosc == search || search == null);
            }

            switch (sort)
            {
                case "descending id":
                    records = records.OrderByDescending(x => x.id_autora);
                    break;

                case "descending imie":
                    records = records.OrderByDescending(x => x.imie);
                    break;

                case "Imię":
                    records = records.OrderBy(x => x.imie);
                    break;

                case "descending nazwisko":
                    records = records.OrderByDescending(x => x.nazwisko);
                    break;

                case "Nazwisko":
                    records = records.OrderBy(x => x.nazwisko);
                    break;

                case "descending narodowosc":
                    records = records.OrderByDescending(x => x.narodowosc);
                    break;

                case "Narodowość":
                    records = records.OrderBy(x => x.narodowosc);
                    break;

                case "descending dziela":
                    records = records.OrderByDescending(x => x.liczba_dziel);
                    break;

                case "Liczba Dzieł":
                    records = records.OrderBy(x => x.liczba_dziel);
                    break;
                default:
                    records = records.OrderBy(x => x.id_autora);
                    break;

            }
            return View(records.ToPagedList(page ?? 1, 10));
        

            /*  OLD VERSION WITHOUT SORTING(JUST SEARCHING)
        
            //if a user choose the radio button option as Imię  
            if (option == "Imię")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(db.autorzy.Where(x => x.imie == search || search == null).ToList().ToPagedList(page ?? 1, 5));
            }
            else if (option == "Nazwisko")
            {
                return View(db.autorzy.Where(x => x.nazwisko == search || search == null).ToList().ToPagedList(page ?? 1, 5));
            }
            else if (option == "Narodowość")
            {
                return View(db.autorzy.Where(x => x.narodowosc == search || search == null).ToList().ToPagedList(page ?? 1, 5));
            }
            else
            {
                return View(db.autorzy.ToList().ToPagedList(page ?? 1, 5));
            }


            */
        }

        // GET: autorzy/Details/5
        public ActionResult Details(int? id, string sort)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            autorzy autorzy = db.autorzy.Find(id);
            if (autorzy == null)
            {
                return HttpNotFound();
            }
            return View(autorzy);
        }

        // GET: autorzy/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: autorzy/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_autora,imie,nazwisko,narodowosc,liczba_dziel,zyciorys")] autorzy autorzy)
        {
            if (ModelState.IsValid)
            {
                autorzy.liczba_dziel = 0;
                db.autorzy.Add(autorzy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(autorzy);
        }

        // GET: autorzy/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            autorzy autorzy = db.autorzy.Find(id);
            if (autorzy == null)
            {
                return HttpNotFound();
            }
            return View(autorzy);
        }

        // POST: autorzy/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_autora,imie,nazwisko,narodowosc,liczba_dziel,zyciorys")] autorzy autorzy)
        {
            if (ModelState.IsValid)
            {
                autorzy.liczba_dziel = db.ksiazki.Where(x => x.id_autora == autorzy.id_autora).Select(x => x.id_ksiazki).Count();
                db.Entry(autorzy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(autorzy);
        }

        // GET: autorzy/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            autorzy autorzy = db.autorzy.Find(id);
            if (autorzy == null)
            {
                return HttpNotFound();
            }
            return View(autorzy);
        }

        // POST: autorzy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                autorzy autorzy = db.autorzy.Find(id);
                db.autorzy.Remove(autorzy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (SqlException)
            {
                return View("DeleteError");
            }
            catch (Exception)
            {
                return View("DeleteError");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Biblioteka_bazyDanych/Controllers/gatunkiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Biblioteka_bazyDanych;
using PagedList;
using PagedList.Mvc;

namespace Biblioteka_bazyDanych.Controllers
{
    public class gatunkiController : Controller
    {
        private bibliotekaEntities1 db = new bibliotekaEntities1();

        // GET: gatunki
        public ActionResult Index(string option, string search, int? page, string sort)
        {
            List<SelectListItem> searchOptions = new List<SelectListItem>();
            var data = new[]{
                 new SelectListItem{ Value="",Text=""},
                 new SelectListItem{ Value="Nazwa" ,Text="Nazwa"},
             };
            searchOptions = data.ToList();

            ViewBag.option = searchOptions;

            ViewBag.SortByName = string.IsNullOrEmpty(sort) ? "descending name" : "";

            //here we are converting the db.autorzy to AsQueryable so that we can invoke all the extension methods on variable records.  
            var records = db.gatunki.AsQueryable();

            if (option == "Nazwa")
            {
                records = records.Where(x => x.nazwa == search || search == null);
            }

            switch (sort)
            {
                case "descending name":
                    records = records.OrderByDescending(x => x.nazwa);
                    break;

                default:
                    records = records.OrderBy(x => x.nazwa);
                    break;

            }
            return View(records.ToPagedList(page ?? 1, 10));

        }

        // GET: gatunki/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            gatunki gatunki = db.gatunki.Find(id);
            if (gatunki == null)
            {
                return HttpNotFound();
            }
            return View(gatunki);
        }

        // GET: gatunki/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: gatunki/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "nazwa")] gatunki gatunki)
        {
            if (ModelState.IsValid)
            {
                db.gatunki.Add(gatunki);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gatunki);
        }

        // GET: gatunki/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            gatunki gatunki = db.gatunki.Find(id);
            if (gatunki == null)
            {
                return HttpNotFound();
            }
            return View(gatunki);
        }

        // POST: gatunki/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "nazwa")] gatunki gatunki)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gatunki).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gatunki);
        }

        // GET: gatunki/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            gatunki gatunki = db.gatunki.Find(id);
            if (gatunki == null)
            {
                return HttpNotFound();
            }
            return View(gatunki);
        }

        // POST: gatunki/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            gatunki gatunki = db.gatunki.Find(id);
            db.gatunki.Remove(gatunki);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Biblioteka_bazyDanych/Views/autorzy/Create.cshtml
@model Biblioteka_bazyDanych.autorzy

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Autorzy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.narodowosc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.narodowosc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.narodowosc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.zyciorys, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.zyciorys, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zyciorys, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Biblioteka_bazyDanych/Views/autorzy/Delete.cshtml
@model Biblioteka_bazyDanych.autorzy

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Autorzy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.narodowosc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.narodowosc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.liczba_dziel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.liczba_dziel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zyciorys)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zyciorys)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Biblioteka_bazyDanych/Views/autorzy/Details.cshtml
@model Biblioteka_bazyDanych.autorzy

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Autorzy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.narodowosc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.narodowosc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.liczba_dziel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.liczba_dziel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zyciorys)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zyciorys)
        </dd>

    </dl>
</div>

<h3>Lista książek</h3>

@if (Model.ksiazki.Count() == 0)
{

    <h5>Autor nie napisał jeszcze książki ;-)</h5>

}



else
{
<table class="table">
    <tr>
        <th>
            ID
        </th>
        <th>
            Tytuł
        </th>
        <th>
            Autor
        </th>
        <th>
            Gatunek
        </th>
        <th>
            Wydawnictwo
        </th>
    </tr>
    @foreach (var item in Model.ksiazki)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id_ksiazki)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tytul)
            </td>
            <td>
                @Html.ActionLink(item.autorzy.imie + " " + item.autorzy.nazwisko, "Details", "autorzy", new { id = item.id_autora }, null)

            </td>
            <td>

                @Html.ActionLink(item.gatunek, "Details", "gatunki", new { id = item.gatunek }, null)
            </td>
            <td>
                @Html.ActionLink(item.wydawnictwo, "Details", "wydawnictwa", new { id = item.wydawnictwo }, null)
            </td>
        </tr>
    }
</table>
}

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_autora }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Biblioteka_bazyDanych/Views/autorzy/Edit.cshtml
@model Biblioteka_bazyDanych.autorzy

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Autorzy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_autora)

        <div class="form-group">
            @Html.LabelFor(model => model.imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.narodowosc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.narodowosc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.narodowosc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.zyciorys, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.zyciorys, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zyciorys, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Biblioteka_bazyDanych/Views/autorzy/Index.cshtml
@using PagedList;

@using PagedList.Mvc;

@model IPagedList<Biblioteka_bazyDanych.autorzy>

@{
    ViewBag.Title = "Index";
}

<h2>Autorzy</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Autorzy", FormMethod.Get))
{
    //the following are search options
    <b> Wyszukaj wg elementu: </b>
    @Html.DropDownList("option", null, htmlAttributes: new { @class = "form-controlSearch" })
    @Html.TextBox("search", null, htmlAttributes: new { @class = "form-controlSearch" }) <input type="submit" name="submit" value="Szukaj" />
}

<br />
<table class="table">
    <tr>
        <th>
            <!-- As "ID" or "Imię" we can also use variables for different languages-->
            @Html.ActionLink("ID", "Index", new
            {
                sort = ViewBag.SortByID,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
            <!--Html.DisplayNameFor(model => model.First().id_autora)-->
        </th>
        <th>
            @Html.ActionLink("Imię", "Index", new
            {
                sort = ViewBag.SortByName,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
        </th>
        <th>
            @Html.ActionLink("Nazwisko", "Index", new
            {
                sort = ViewBag.SortBySurname,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
        </th>
        <th>
            @Html.ActionLink("Narodowość", "Index", new
            {
                sort = ViewBag.SortByNationality,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
        </th>
        <th>
            @Html.ActionLink("Liczba Dzieł", "Index", new
            {
                sort = ViewBag.SortByBooks,
                option = Request.QueryString["option"],
                search = Request.QueryString["search"]
            })
        </th>
        <th></th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="6"> Brak wyników pasujących do kryterium wyszukiwania </td>
        </tr>
    }
    else
    {

        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id_autora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.imie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nazwisko)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.narodowosc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.liczba_dziel)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id_autora }) |
                    @Html.ActionLink("Details", "Details", new { id = item.id_autora }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id_autora })
                </td>
            </tr>
        }
    }
</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new
{
page,
option = Request.QueryString["option"],  
search = Request.QueryString["search"],
sort = Request.QueryString["sort"]  
}))